language: python
python:
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: cloudperf write_prices --s3-bucket cloudperf-data --file /tmp/prices.json.gz --no-update
